name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

env:
    PROJECT_NAME: fanqie

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - id: commit-hash
              uses: prompt/actions-commit-hash@v3

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Ninja
              uses: ashutoshvarma/setup-ninja@master
              with:
                  version: 1.10.0

            - name: Set up MinGW
              uses: egor-tensin/setup-mingw@v2
              with:
                  platform: x64

            - name: Linux Build
              run: |
                  echo "Build with commit hash ${{ steps.commit-hash.outputs.short }}"
                  cmake --preset=Linux
                  cmake --build ./build/Linux -j

            - name: Windows Build
              run: |
                  echo "Build with commit hash ${{ steps.commit-hash.outputs.short }}"
                  cmake --preset=Windows
                  cmake --build ./build/Windows -j

            - name: Linux Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Linux-${{ steps.commit-hash.outputs.short }}
                  path: ./build/Linux/${{ env.PROJECT_NAME }}.so

            - name: Windows Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Windows-${{ steps.commit-hash.outputs.short }}
                  path: ./build/Windows/${{ env.PROJECT_NAME }}.dll

            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  name: Release ${{ github.ref }}
                  files: |
                      ./build/Windows/${{ env.PROJECT_NAME }}.dll
                      ./build/Linux/${{ env.PROJECT_NAME }}.so
